### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by t880216t** [talamortis/mod_character_tools#1]
sir ,  
i had build this mod in my server, but i don't how to use it .
is it  need some sql file ? could you give a example .
tks

**Comment by talamortis** [comment]
`INSERT INTO `item_template` VALUES (90010, 0, 0, 0, 'Character tools', 46787, 6, 0, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 18282, 0, 0, 0, 8000, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, '|cff00FF00Use: Customize your character|r', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 'character_tools', 0, 0, 0, 0, 0, -4);  `

**Comment by t880216t** [comment]
Yeah , i get it .
tks
